
    create table notificacion_medios (
        notificacion_id bigint not null,
        medio varchar(255) check (medio in ('EMAIL','SMS','APP_PUSH'))
    );

    create table notificaciones (
        id bigint generated by default as identity,
        momento_real_envio timestamp(6),
        programacion_envio timestamp(6),
        asunto varchar(255),
        cuerpo TEXT,
        email_destino varchar(255),
        estado varchar(255) check (estado in ('PENDIENTE','ENVIADA','ERROR')),
        mensaje_error varchar(255),
        telefono_destino varchar(255),
        tipo_notificacion varchar(255) check (tipo_notificacion in ('ANUNCIO_NOTA_ESTUDIANTE','ANUNCIO_AULA_ESTUDIANTE','ANUNCIO_AULA_VIGILANTE','PASSWORD_RESET')),
        primary key (id)
    );

    alter table if exists notificacion_medios 
       add constraint FK59s9jf0imqund4vgf5hqs8nxr 
       foreign key (notificacion_id) 
       references notificaciones;

    create table notificacion_medios (
        notificacion_id bigint not null,
        medio varchar(255) check (medio in ('EMAIL','SMS','APP_PUSH'))
    );

    create table notificaciones (
        id bigint generated by default as identity,
        momento_real_envio timestamp(6),
        programacion_envio timestamp(6),
        asunto varchar(255),
        cuerpo TEXT,
        email_destino varchar(255),
        estado varchar(255) check (estado in ('PENDIENTE','ENVIADA','ERROR')),
        mensaje_error varchar(255),
        telefono_destino varchar(255),
        tipo_notificacion varchar(255) check (tipo_notificacion in ('ANUNCIO_NOTA_ESTUDIANTE','ANUNCIO_AULA_ESTUDIANTE','ANUNCIO_AULA_VIGILANTE','PASSWORD_RESET')),
        primary key (id)
    );

    alter table if exists notificacion_medios 
       add constraint FK59s9jf0imqund4vgf5hqs8nxr 
       foreign key (notificacion_id) 
       references notificaciones;

    create table notificacion_medios (
        notificacion_id bigint not null,
        medio varchar(255) check (medio in ('EMAIL','SMS','APP_PUSH'))
    );

    create table notificaciones (
        id bigint generated by default as identity,
        momento_real_envio timestamp(6),
        programacion_envio timestamp(6),
        asunto varchar(255),
        cuerpo TEXT,
        email_destino varchar(255),
        estado varchar(255) check (estado in ('PENDIENTE','ENVIADA','ERROR')),
        mensaje_error varchar(255),
        telefono_destino varchar(255),
        tipo_notificacion varchar(255) check (tipo_notificacion in ('ANUNCIO_NOTA_ESTUDIANTE','ANUNCIO_AULA_ESTUDIANTE','ANUNCIO_AULA_VIGILANTE','PASSWORD_RESET')),
        primary key (id)
    );

    alter table if exists notificacion_medios 
       add constraint FK59s9jf0imqund4vgf5hqs8nxr 
       foreign key (notificacion_id) 
       references notificaciones;

    create table notificacion_medios (
        notificacion_id bigint not null,
        medio varchar(255) check (medio in ('EMAIL','SMS','APP_PUSH'))
    );

    create table notificaciones (
        id bigint generated by default as identity,
        momento_real_envio timestamp(6),
        programacion_envio timestamp(6),
        asunto varchar(255),
        cuerpo TEXT,
        email_destino varchar(255),
        estado varchar(255) check (estado in ('PENDIENTE','ENVIADA','ERROR')),
        mensaje_error varchar(255),
        telefono_destino varchar(255),
        tipo_notificacion varchar(255) check (tipo_notificacion in ('ANUNCIO_NOTA_ESTUDIANTE','ANUNCIO_AULA_ESTUDIANTE','ANUNCIO_AULA_VIGILANTE','PASSWORD_RESET')),
        primary key (id)
    );

    alter table if exists notificacion_medios 
       add constraint FK59s9jf0imqund4vgf5hqs8nxr 
       foreign key (notificacion_id) 
       references notificaciones;

    create table notificacion_medios (
        notificacion_id bigint not null,
        medio varchar(255) check (medio in ('EMAIL','SMS','APP_PUSH'))
    );

    create table notificaciones (
        id bigint generated by default as identity,
        momento_real_envio timestamp(6),
        programacion_envio timestamp(6),
        asunto varchar(255),
        cuerpo TEXT,
        email_destino varchar(255),
        estado varchar(255) check (estado in ('PENDIENTE','ENVIADA','ERROR')),
        mensaje_error varchar(255),
        telefono_destino varchar(255),
        tipo_notificacion varchar(255) check (tipo_notificacion in ('ANUNCIO_NOTA_ESTUDIANTE','ANUNCIO_AULA_ESTUDIANTE','ANUNCIO_AULA_VIGILANTE','PASSWORD_RESET')),
        primary key (id)
    );

    alter table if exists notificacion_medios 
       add constraint FK59s9jf0imqund4vgf5hqs8nxr 
       foreign key (notificacion_id) 
       references notificaciones;

    create table notificacion_medios (
        notificacion_id bigint not null,
        medio varchar(255) check (medio in ('EMAIL','SMS','APP_PUSH'))
    );

    create table notificaciones (
        id bigint generated by default as identity,
        momento_real_envio timestamp(6),
        programacion_envio timestamp(6),
        asunto varchar(255),
        cuerpo TEXT,
        email_destino varchar(255),
        estado varchar(255) check (estado in ('PENDIENTE','ENVIADA','ERROR')),
        mensaje_error varchar(255),
        telefono_destino varchar(255),
        tipo_notificacion varchar(255) check (tipo_notificacion in ('ANUNCIO_NOTA_ESTUDIANTE','ANUNCIO_AULA_ESTUDIANTE','ANUNCIO_AULA_VIGILANTE','PASSWORD_RESET')),
        primary key (id)
    );

    alter table if exists notificacion_medios 
       add constraint FK59s9jf0imqund4vgf5hqs8nxr 
       foreign key (notificacion_id) 
       references notificaciones;
